#jms_serializer:
#    visitors:
#        xml_serialization:
#            format_output: '%kernel.debug%'
#    property_naming:
#        lower_case: true
#    metadata:
#        auto_detection: true
#        directories:
#            FOSUB:
#                namespace_prefix: 'FOS\UserBundle'
#                path: '%kernel.root_dir%/Serializer'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
