#config/packages/security.yaml
security:
    encoders:
        #FOS\UserBundle\Model\UserInterface: auto
        App\Entity\User:
            algorithm: auto


    role_hierarchy:
        ROLE_AMBASSADOR:    ROLE_USER
        ROLE_ADMIN:         ROLE_AMBASSADOR
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [app_user_provider, in_memory]
        in_memory:
            memory:
                users:
                    superadmin:
                        password: 'a'
                        roles: ['ROLE_SUPER_ADMIN']
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)

    access_control:
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern:  ^/api/auth/login
            stateless: true
            anonymous: true
            json_login:
                provider: chain_provider
                check_path:               /api/auth/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            provider: chain_provider
        api_register:
            pattern:  ^/api/auth/register
            stateless: true
            anonymous: true
        api_doc:
            pattern:  ^/api/doc
            stateless: true
            anonymous: true
        api:
            pattern: ^/api
            stateless: true
            anonymous: false
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            anonymous:    true
            logout:
                path:   app_logout
                target: api_login
