api_login_check:
  path: /api/{_locale}/auth/login_check
  methods: [POST]
  requirements:
    _locale: en|fr

mediaobject:
     type:     annotation
     resource: App\Controller\MediaObjectController